# Generated by Django 4.1 on 2022-08-24 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("adds", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="Post_category",
                to="adds.category",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="phonenumber",
            name="phone_number_0",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="post",
            name="email",
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Subscription",
                to="adds.post",
            ),
        ),
    ]
